# Generated by Django 5.2.6 on 2025-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_patrimonio', models.CharField(max_length=64, unique=True, verbose_name='Código do Patrimônio')),
                ('data', models.DateField(verbose_name='Data')),
                ('checklist', models.TextField(blank=True, verbose_name='Checklist')),
                ('localizacao', models.CharField(blank=True, max_length=128, verbose_name='Localização')),
                ('filial', models.CharField(blank=True, max_length=128, verbose_name='Filial')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
