# Generated by Django 5.2.6 on 2025-09-29 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='client_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='content_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='dropbox_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='dropbox_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='ocr_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='processado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='checklist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='cod_patrimonio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='filial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
