# Generated by Django 5.2.6 on 2025-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_patrimonio_arquivo_patrimonio_client_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='checklist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='cod_patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
