# Generated by Django 5.2.6 on 2025-10-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_patrimonio_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='coords_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='coords_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='coords_raw',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
